[tool.poetry]
name = "telegrinder"
version = "0.1.0"
description = "Grinding telegram events – customizable tool to build telegram bots"
authors = ["timoniq <tesseradecades@mail.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"
pydantic = "^1.9.0"
vbml = "^1.1.post1"
choicelib = "^0.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
