blank_issues_enabled: false
contact_links:
  - name: \U0001F4AC Telegram forum \U0001F4AC
    url: https://t.me/botoforum/148235
    about: \u270f\ufe0f You can ask questions about the framework. \u270f\ufe0f